const MIN_BID_AMOUNT = 50;
const MAX_BID_AMOUNT = 500;
const MIN_ROOM_DESCRIPTION_LENGTH = 100;
const MAX_ROOM_DESCRIPTION_LENGTH = 400;

exports.MAX_BID_AMOUNT = MAX_BID_AMOUNT
exports.MIN_BID_AMOUNT = MIN_BID_AMOUNT
exports.MIN_ROOM_DESCRIPTION_LENGTH = MIN_ROOM_DESCRIPTION_LENGTH
exports.MAX_ROOM_DESCRIPTION_LENGTH = MAX_ROOM_DESCRIPTION_LENGTH